
export const LESSONS = [
    // 1. Ôn tập và bổ sung
    "Bài 1. Ôn tập các số đến 100 000",
    "Bài 2. Ôn tập phép cộng, phép trừ",
    "Bài 3. Ôn tập phép nhân, phép chia",
    "Bài 4. Số chẵn, số lẻ",
    "Bài 6. Bài toán liên quan đến rút về đơn vị",
    "Bài 8. Bài toán giải bằng ba bước tính",
    "Bài 9. Ôn tập biểu thức số",
    "Bài 10. Biểu thức có chứa chữ",
    "Bài 13. Tính chất giao hoán, kết hợp của phép cộng",
    "Bài 14. Tính chất giao hoán, kết hợp của phép nhân",
    "Bài 16. Dãy số liệu",
    "Bài 17. Biểu đồ cột",
    "Bài 18. Số lần lặp lại của một sự kiện",
    "Bài 19. Tìm số trung bình cộng",
    "Bài 20. Đề-xi-mét vuông",
    "Bài 21. Mét vuông",
    // 2. SỐ TỰ NHIÊN
    "Bài 24. Các số có sáu chữ số - Hàng và lớp",
    "Bài 25. Triệu – Lớp triệu",
    "Bài 26. Đọc, viết các số tự nhiên trong hệ thập phân",
    "Bài 27. So sánh và xếp thứ tự các số tự nhiên",
    "Bài 28. Dãy số tự nhiên",
    "Bài 30. Đo góc – Góc nhọn, góc tù, góc bẹt",
    "Bài 31. Hai đường thẳng vuông góc",
    "Bài 32. Hai đường thẳng song song",
    "Bài 34. Giây",
    "Bài 35. Thế kỉ",
    "Bài 36. Yến, tạ, tấn",
    // 3. CÁC PHÉP TÍNH VỚI SỐ TỰ NHIÊN
    "Bài 40. Phép cộng các số tự nhiên",
    "Bài 41. Phép trừ các số tự nhiên",
    "Bài 42. Tìm hai số khi biết tổng và hiệu của hai số đó",
    "Bài 44. Nhân với số có một chữ số",
    "Bài 45. Nhân và Chia cho 10, 100, 1 000,...",
    "Bài 46. Nhân các số có tận cùng là chữ số 0",
    "Bài 49. Chia cho số có một chữ số",
    "Bài 50. Chia hai số có tận cùng là chữ số 0",
    "Bài 51. Ước lượng thương trong phép chia",
    "Bài 52. Chia cho số có hai chữ số",
    "Bài 54. Hình bình hành",
    "Bài 55. Hình thoi",
    "Bài 57. Mi-li-mét vuông",
    // 4. PHÂN SỐ
    "Bài 60. Phân số",
    "Bài 61. Phân số và phép chia số tự nhiên",
    "Bài 62. Phân số bằng nhau",
    "Bài 63. Rút gọn phân số",
    "Bài 65. Quy đồng mẫu số các phân số",
    "Bài 66. So sánh hai phân số",
    "Bài 68. Cộng hai phân số cùng mẫu số",
    "Bài 69. Cộng hai phân số khác mẫu số",
    "Bài 71. Trừ hai phân số cùng mẫu số",
    "Bài 72. Trừ hai phân số khác mẫu số",
    "Bài 74. Phép nhân phân số",
    "Bài 75. Phép chia phân số",
    "Bài 76. Tìm phân số của một số",
];
